DROP USER U_SGKIRB2Z CASCADE;
DROP USER LOCB1 CASCADE;
DROP USER LOCB4 CASCADE;
DROP USER LOCB5 CASCADE;
DROP USER LOCB6 CASCADE;
DROP USER LOCB7 CASCADE;
DROP USER LOCB71 CASCADE;
DROP USER LOCKT CASCADE;
DROP USER U_SGKIRB2W CASCADE;
DROP USER U_SGKIRB2Y CASCADE;
DROP USER U_SGKIRB4H CASCADE;

SELECT username, profile FROM dba_users WHERE username IN ('U_SGKIRB2Y','SYS','SYSTEM');

GRANT EXECUTE ON DBMS_ALERT TO locb2 with grant option;

CREATE USER APPLOGGER IDENTIFIED BY "locb2";
GRANT CREATE SESSION TO APPLOGGER;

GRANT INSERT ON LOCB2.LOGIN_ATTEMPTS TO APPLOGGER;
GRANT INSERT ON LOCB2.LOGS TO APPLOGGER;
GRANT SELECT ON LOCB2.USERS TO APPLOGGER;
GRANT EXECUTE ON LOCB2.record_login_attempt_proc TO APPLOGGER;
GRANT EXECUTE ON LOCB2.insert_record_generic TO APPLOGGER;

GRANT EXECUTE ON DBMS_CRYPTO TO locb2;
grant execute on locb2.JAVA_GENERATE_KEYS TO PUBLIC;
GRANT EXECUTE ON LOCB2.RSA_ENCRYPT_JAVA TO PUBLIC;
GRANT EXECUTE ON LOCB2.RSA_DECRYPT_JAVA TO PUBLIC;

SET SERVEROUTPUT ON;

GRANT SELECT ON dba_audit_trail TO LOCB2;
GRANT SELECT ON v_$session TO LOCB2;
